# syntax=docker/dockerfile:1

FROM python:3.10-slim

WORKDIR /src

#COPY LimitOrderBook LimitOrderBook
#COPY manage.py .
COPY requirements.txt .

RUN apt update \
    && apt install -y build-essential python3-dev default-libmysqlclient-dev\
    && python -m pip install --upgrade pip \
    && pip install -r requirements.txt

#CMD ./manage.py runserver

