# syntax=docker/dockerfile:1

FROM python:3.10-alpine3.16

WORKDIR /src

COPY LimitOrderBook LimitOrderBook
COPY manage.py .
COPY requirements.txt .

RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev \
    && python -m pip install --upgrade pip \
    && pip install -r requirements.txt

EXPOSE 8000

CMD ./manage.py runserver

