[project]
name = "tradeengine"
version = "0.1.0"
description = "Python trade engine"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "ruff>=0.14.1",
    "sortedcontainers>=2.4.0",
]
